name: Publish Stack Set to Service Catalog
# On a relase via manual execution this workflow will 
# Synth the CloudFormation templates from the typescript cdk run jests tests
# against the resultant files and confirm they contain the expected resources.
# The Synth will run again and if a difference is found they will update the
# Service Catalog Stack Set. 
on:
  push:
    branches:
      - vf/plat-1529
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    needs: 
      - validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.81.0'
          working_dir: 'cdk.out'
      - name: Hyphenate Version
        id: hyphenate-version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          RELEASE=$(echo $VERSION | sed s/\\./-/g)
          echo "release=$RELEASE" >> "$GITHUB_OUTPUT"
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DT_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Delete previous stackset
        run: |
          previous=$(aws cloudformation list-stack-sets --status ACTIVE --query "Summaries[*].StackSetName" | \
          grep di-devplat-obv-dynatrace-iam | sed -e 's/^[ \t]*//' | tr -d '"')
        env:
          AWS_DEFAULT_REGION: 'eu-west-2'
